version = 1

# ------------------------
# Analyzers
# ------------------------

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "browser",
    "nodejs",
    "jest"
  ]

# ------------------------
# Exclusions
# ------------------------

exclude_patterns = [
  "node_modules/**",
  "dist/**",
  "build/**",
  "coverage/**",
  "public/**",
  "**/*.config.js",
  "**/*.config.ts",
  "vite.config.ts"
]
